backendReplicas: 1
frontendReplicas: 1
container_repo: localhost:5000/week07
frontendPort: 80
mysqlPort: 3306

common:
  log_level: INFO
  log_format: "%(asctime)-15s - %(name)s - %(levelname)s  %(message)s"

data_config:
  news_url: https://book.douban.com/subject/34786086
  comments_url: https://book.douban.com/subject/34786086/comments/new
  comments_per_page: 20
  max_pages: 10
  download_delay: 5
  process_interval: 3600

backend_config:
  page_size: 25
  ok_code: 200
  positive_threshold: 0.6