apiVersion: v1
kind: Service
metadata:
  name: newscomments-data
  namespace: {{ .Release.Namespace }}
  labels:
    app: newscomments
    tier: data
spec:
  type: ClusterIP
  selector:
    app: newscomments
    tier: data
  ports:
  - port: 9090
    targetPort: http-server
